const FETCH_BLOCKS = 'FETCH_BLOCKS';
const FETCH_SINGLE_BLOCK = 'FETCH_SINGLE_BLOCK';
const FETCH_LATEST = 'FETCH_LATEST';
const FETCH_TRANSACTIONS = 'FETCH_TRANSACTIONS';
const FETCH_MINING = 'FETCH_MINING';

module.exports = {
  FETCH_BLOCKS, FETCH_LATEST, FETCH_TRANSACTIONS, FETCH_MINING, FETCH_SINGLE_BLOCK,
};
