const FETCH_BLOCKS = 'FETCH_BLOCKS';
const FETCH_LATEST = 'FETCH_LATEST';
const FETCH_TRA = 'FETCH_TRA';
const FETCH_MINING = 'FETCH_MINING';

module.exports = FETCH_BLOCKS, FETCH_LATEST, FETCH_TRA, FETCH_MINING;

